tests: geting failing tests predictions from test-predictor (#16799)
* tests: geting failing tests predictions from test-predictor

The idea of this change is to start showing execution predictions for
the failing tests. The results won't take into account the last set of
results as the algorithm is not trained with those results yet.

* fix predict client url

* missing changes for indentation

* make wget quiet

diff --git a/.github/workflows/spread-tests.yaml b/.github/workflows/spread-tests.yaml
--- a/.github/workflows/spread-tests.yaml
+++ b/.github/workflows/spread-tests.yaml
@@ -588,10 +588,16 @@ jobs:
               -F "job_id=$JOB_ID" \
               -F "run_id=${{ github.run_id }}")
 
-              if [[ ! $HTTP_CODE =~ ^2[0-9]{2}$ ]]; then
-                  echo "Request failed with status $HTTP_CODE"
-                  exit 1
-              fi
+            if [[ ! $HTTP_CODE =~ ^2[0-9]{2}$ ]]; then
+                echo "Request failed with status $HTTP_CODE"
+                exit 1
+            fi
+            echo "Results sent successfully"
+
+            echo "Getting predictions for failed tests"
+            wget -q -O predict https://raw.githubusercontent.com/canonical/snapd-testing/master/ai/test-predictor/client/predict
+            chmod +x predict
+            ./predict results.json
         else
             echo "No spread results log found, skipping sending results to Test-Predictor"
         fi
